name: main

on:
  push:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Set up docker cache
        uses: actions/cache@v3
        with:
          path: /var/lib/docker
          key: ${{ runner.os }}-docker
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build monitor
        run: docker build -t monitor .
      - name: Deploy monitor branch
        if: ${{ github.ref_type == 'branch' && github.ref_name == vars.CI_BRANCH && github.event_name != 'pull_request' }}
        run: |
          TAG=${GITHUB_REF_NAME}
          docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }} docker.io
          docker buildx create --use || true
          docker buildx build --platform linux/arm/v7,linux/arm64/v8,linux/amd64 -t docker.io/shajen/monitor:$TAG --push .
      - name: Deploy monitor tag
        if: ${{ github.ref_type == 'tag' }}
        run: |
          TAG=${GITHUB_REF_NAME/v/}
          docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }} docker.io
          docker buildx create --use || true
          docker buildx build --platform linux/arm/v7,linux/arm64/v8,linux/amd64 -t docker.io/shajen/monitor:$TAG -t docker.io/shajen/monitor --push .
